# Copyright 2026 labring.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: internal-user-admission
  namespace: internal-credential-broker
rules:
- apiGroups: [user.sealos.io]
  resources: [credentialleases]
  verbs: [get]
