user:
- 'controllers/user/**'

account:
- 'controllers/account/**'

app:
- 'controllers/app/**'

db-adminer:
- 'controllers/db/adminer/**'

devbox:
- 'controllers/devbox/**'

job:
- 'controllers/job/**'

license:
- 'controllers/license/**'

node:
- 'controllers/node/**'

objectstorage:
- 'controllers/objectstorage/**'

resources:
- 'controllers/resources/**'

terminal:
- 'controllers/terminal/**'

webhook:
- 'webhooks/admission/**'

account-service:
- 'services/account/**'

database-service:
- 'services/database/**'

devbox-service:
- 'services/devbox/**'

exceptionmonitor-service:
- 'services/exceptionmonitor/**'

launchpad-service:
- 'services/launchpad/**'

minio-service:
- 'services/minio/**'

pay-service:
- 'services/pay/**'

vlogs-service:
- 'services/vlogs/**'
