# Copyright 2026 labring.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: internal-credential-broker
rules:
- apiGroups: [user.sealos.io]
  resources: [internalusers]
  verbs: [get]
- apiGroups: [user.sealos.io]
  resources: [credentialleases]
  verbs: [get, create]
- apiGroups: [user.sealos.io]
  resources: [credentialleases/status]
  verbs: [get, update, patch]
- apiGroups: [authentication.k8s.io]
  resources: [tokenreviews]
  verbs: [create]
