# Copyright 2026 labring.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: internal-credential-broker-tokenrequest
  namespace: internal-user-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: internal-credential-broker-tokenrequest
subjects:
- kind: ServiceAccount
  name: internal-credential-broker
  namespace: internal-credential-broker
