# Copyright 2026 labring.
apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-user-controller-config
  namespace: internal-user-controller
data:
  oidc-issuers: https://replace-with-allowlisted-oidc-issuer.example
