# Copyright 2026 labring.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal-credential-approval-adapter-selfsigned
  namespace: internal-credential-approval
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-credential-approval-adapter-tls
  namespace: internal-credential-approval
spec:
  secretName: internal-credential-approval-adapter-tls
  dnsNames:
  - internal-credential-approval-adapter.internal-credential-approval.svc
  - internal-credential-approval-adapter.internal-credential-approval.svc.cluster.local
  issuerRef:
    name: internal-credential-approval-adapter-selfsigned
    kind: Issuer
