# syntax=docker/dockerfile:1
FROM golang:1.24 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH:-amd64} go build -buildvcs=false -ldflags "-s -w" -trimpath -o /out/approval-adapter ./cmd/internal-user-approval-adapter

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/approval-adapter /approval-adapter
USER nonroot:nonroot
ENTRYPOINT ["/approval-adapter"]
