name: Interact with Sealos robot using issue comments
on:
  issue_comment:
    types:
      - created
jobs:
  comment:
    permissions:
      issues: write
    if: startswith(github.event.comment.body, '/')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v4
      - name: Gh Robot for Sealos
        uses: labring/robot@v2.0.0
        with:
          version: v2.0.0
        env:
          SEALOS_TYPE: "/comment"
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
