
name: Check and resolve controller code

on:
  push:
    branches: [ "main" ]
    paths:
      - "controllers/**"  
env:
  # Common versions
  GO_VERSION: "1.22"
  DEFAULT_OWNER: "labring"
jobs:
  golangci-lint:
    if: ${{ github.event_name }} == 'push'
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false    
      matrix:
        module:
          - { name: user, path: user } #TODO: maybe we should detect modules with a script
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          working-directory: controllers/${{ matrix.module.path }}
          args: "--out-${NO_FUTURE}format colored-line-number"