name:  Controller workflow entry after receiving pull request event
on:
  pull_request:
    branches: [ "*" ]
    paths:
      - "controllers/"

jobs:
  start-workflow:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/controller.yml
    with:
      needs_push: false
      needs_cluster_image: false