name:  Controller workflow entry after receiving push event
on:
  push:
    branches: [ "main" ]
    paths:
      - "controllers/"

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-controller.yml
    with:
      needs_push: true