
name: Default controller workflow

on:
  workflow_call:
    inputs:
      module_name:
        description: "The name of the controller"
        required: true
        type: string
      module_path:
        description: "The path of the controller under `workdir` (it should be one of the subdirectories)"
        required: true
        type: string
      workdir:
        description: "The directory to find the controller"
        required: true
        type: string
      needs_push:
        description: "If this parameter is true, this workflow will push the image after building it"
        required: false
        type: boolean
        default: false
      push_image_tag:
        description: "The tag for the image to push"
        default: "latest"
        required: false
        type: string
      needs_cluster_image:
        description: "If this parameter is true, this workflow will build and push the image after building it"
        required: false
        type: boolean
        default: false
jobs:
  run-linter:
    uses: ./.github/workflows/golangci-lint.yml
    with:
      module_path: ${{ inputs.module_path }}
      workdir: ${{ inputs.workdir }}
      version: "1.22"
  build-controller-image:
    needs: [run-linter]
    uses: ./.github/workflows/build-controller-image.yml
    with:
      module_name: ${{ inputs.module_name }}
      module_path: ${{ inputs.module_path }}
      workdir: ${{ inputs.workdir }}
      needs_push: ${{ inputs.needs_push }}
      push_image_tag: ${{ inputs.push_image_tag }}
  build-controller-cluster-image:
    if: ${{ inputs.needs_cluster_image }} && ${{ inputs.needs_push }}
    needs: [build-controller-image]
    uses: ./.github/workflows/build-controller-cluster-image.yml
    with:
      module_name: ${{ inputs.module_name }}
      module_path: ${{ inputs.module_path }}
      workdir: ${{ inputs.workdir }}
      needs_push: ${{ inputs.needs_push }}
      push_image_tag: ${{ inputs.push_image_tag }} 