name: Generate controller module matrix
on:
  workflow_call:
    outputs:
      modules:
        description: "JSON array of modules"
        value: ${{ jobs.generate-matrix.outputs.modules }}

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-output.outputs.modules }}
    steps:
      - name: Export matrix as JSON
        id: set-output
        run: |
          set -eux
          # TODO: replace this with dynamic discovery
          MODULES='[
            {"name": "user", "path": "user"},
            {"name": "terminal", "path": "terminal"}
          ]'
          MODULES=$(echo $MODULES | jq -c) # format json
          echo "modules=$MODULES" >> $GITHUB_OUTPUT