
name: Default frontend workflow

on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
        default: "sealos"
      module_name:
        required: true
        type: string
      module_path:
        required: true
        type: string
      workdir:
        type: string
        default: "frontend"
      needs_push:
        required: false
        type: boolean
        default: false
      push_image_tag:
        default: "latest"
        required: false
        type: string
      needs_cluster_image:
        required: false
        type: boolean
        default: false
jobs:
  prepare-image-info:
    uses: ./.github/workflows/prepare-image-info.yml
    with:
      module_name: ${{ inputs.module_name }}
      comp: 'frontend'
      needs_push: ${{ inputs.needs_push }}
      push_image_tag: ${{ inputs.push_image_tag }}
  build-image:
    needs: [prepare-image-info]
    uses: ./.github/workflows/build-frontend-image.yml
    with:
      module_name: ${{ inputs.module_name }}
      module_path: ${{ inputs.module_path }}
      workdir: ${{ inputs.workdir }}
      needs_push: ${{ inputs.needs_push }}
      repo: ${{ needs.prepare-image-info.outputs.cur_docker_repo }}
      tag: ${{ needs.prepare-image-info.outputs.tag_name }}
  build-frontend-cluster-image:
    if: ${{ inputs.needs_cluster_image }} && ${{ inputs.needs_push }}
    needs: [build-image, prepare-image-info]
    uses: ./.github/workflows/build-cluster-image.yml
    with:
      module_name: ${{ inputs.module_name }}
      module_path: ${{ inputs.module_path }}
      workdir: ${{ inputs.workdir }}
      sealos_artifact: ${{ inputs.artifact_name }}
      cur_cluster_repo: ${{ needs.prepare-image-info.outputs.cur_cluster_repo }}
      orig_docker_repo: ${{ needs.prepare-image-info.outputs.orig_docker_repo }}
      cur_docker_repo: ${{ needs.prepare-image-info.outputs.cur_docker_repo }}
      tag_name: ${{ needs.prepare-image-info.outputs.tag_name }} 