
name: Default frontend workflow after pull request

on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
      module_path:
        required: true
        type: string
      workdir:
        type: string
        default: "frontend"
jobs:
  prepare-image-info:
    uses: ./.github/workflows/prepare-image-info.yml
    with:
      module_name: ${{ inputs.module_name }}
      comp: 'frontend'
  build-image:
    needs: [prepare-image-info]
    uses: ./.github/workflows/build-frontend-image.yml
    with:
      module_name: ${{ inputs.module_name }}
      module_path: ${{ inputs.module_path }}
      workdir: ${{ inputs.workdir }}
      repo: ${{ needs.prepare-image-info.outputs.cur_docker_repo }}
      tag: ${{ needs.prepare-image-info.outputs.tag_name }}