
name: Default frontend workflow

on:
  workflow_call:
    inputs:
      module_name:
        description: "The name of the frontend"
        required: true
        type: string
      module_path:
        description: "The path of the frontend under `workdir` (it should be one of the subdirectories)"
        required: true
        type: string
      workdir:
        description: "The directory to find the frontend"
        type: string
        default: "frontend"
      needs_push:
        description: "If this parameter is true, this workflow will push the image after building it"
        required: false
        type: boolean
        default: false
      push_image_tag:
        description: "The tag for the image to push"
        default: "latest"
        required: false
        type: string
      needs_cluster_image:
        description: "If this parameter is true, this workflow will build and push the image after building it"
        required: false
        type: boolean
        default: false
jobs:
  build-frontend-image:
    uses: ./.github/workflows/build-frontend-image.yml
    with:
      module_name: ${{ inputs.module_name }}
      module_path: ${{ inputs.module_path }}
      workdir: ${{ inputs.workdir }}
      needs_push: ${{ inputs.needs_push }}
      push_image_tag: ${{ inputs.push_image_tag }}
  build-frontend-cluster-image:
    if: ${{ inputs.needs_cluster_image }} && ${{ inputs.needs_push }}
    needs: [build-frontend-image]
    uses: ./.github/workflows/build-cluster-image.yml
    with:
      artifact_name: "sealos-frontend"
      module_name: ${{ inputs.module_name }}
      module_path: ${{ inputs.module_path }}
      workdir: ${{ inputs.workdir }}
      needs_push: ${{ inputs.needs_push }}
      push_image_tag: ${{ inputs.push_image_tag }} 