name: Run Golang CI linter

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: "1.22"
      modules:
        required: true
        type: string
      workdir:
        required: true
        type: string

jobs:
  golangci-lint:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false    
      matrix:
        module: ${{ fromJSON(inputs.modules) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version: ${{ inputs.version }}
      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          working-directory: ${{ inputs.workdir }}/${{ matrix.module.path }}
          args: "--out-${NO_FUTURE}format colored-line-number"