name: Trusted lifecycle code workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
        - "lifecycle/**"
        - "!**/*.md"
        - "!**/*.yaml"
env:
  # Common versions
  GO_VERSION: "1.23"
  PROJECT_PATH: "./lifecycle"

jobs:
  format-code:
    runs-on: ubuntu-24.04
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Format Code
        env:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
        run: cd "$PROJECT_PATH" && make format

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(fmt): format code"
          commit_options: "-s"
