name: Prepare Image Information
on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
      comp:
        required: true
        type: string
      # TODO: rename this
      needs_push:
        required: false
        type: boolean
        default: false
      # TODO: rename this
      push_image_tag:
        required: false
        type: string
        default: ""
      orig_owner:
        required: false
        type: string
        default: labring
    outputs:
      orig_docker_repo:
        value: ${{ jobs.prepare.outputs.orig_docker_repo }}
      cur_docker_repo:
        value: ${{ jobs.prepare.outputs.cur_docker_repo }}
      orig_cluster_repo:
        value: ${{ jobs.prepare.outputs.orig_cluster_repo }}
      cur_cluster_repo:
        value: ${{ jobs.prepare.outputs.cur_cluster_repo }}
      tag_name:
        value: ${{ jobs.prepare.outputs.tag_name }}

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      orig_docker_repo: ${{ steps.prepare-image-info.outputs.orig_docker_repo }}
      cur_docker_repo: ${{ steps.prepare-image-info.outputs.cur_docker_repo }}
      orig_cluster_repo: ${{ steps.prepare-image-info.outputs.orig_cluster_repo }}
      cur_cluster_repo: ${{ steps.prepare-image-info.outputs.cur_cluster_repo }}
      tag_name: ${{ steps.prepare-tag-info.outputs.tag_name }}
    steps:
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1
      - name: Check if tagged
        id: check_tag
        env:
          REF: ${{ github.ref }}
        run: |
          if [[ "$REF" == refs/tags/* ]]; then
            echo "is_tag=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_tag=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Prepare tag info
        id: prepare-tag-info
        run: |
          SHA_TAG=${GIT_COMMIT_SHORT_SHA}
          tag_name="$SHA_TAG"
          push_image=${{ inputs.needs_push }}
          push_image_tag=${{ inputs.push_image_tag }}
          release=${{ steps.check_tag.outputs.is_tag }}
          if [[ "$push_image" == true ]]; then
            tag_name=${push_image_tag:-latest}
          elif [[ "$release" == true ]]; then
            tag_name=${GITHUB_REF#refs/tags/}
          fi
          echo "tag_name=$tag_name" >> "$GITHUB_OUTPUT"
      - name: Prepare image info
        id: prepare-image-info
        env:
          MODULE_NAME: ${{ inputs.module_name }}
          ORIG_OWNER: ${{ inputs.orig_owner }}
          REPO_OWNER: ${{ github.repository_owner }}
          COMP: ${{ inputs.comp }}
        run: |
          {
            echo "orig_docker_repo=ghcr.io/${ORIG_OWNER}/sealos-${MODULE_NAME}-${COMP}"
            echo "cur_docker_repo=ghcr.io/${REPO_OWNER}/sealos-${MODULE_NAME}-${COMP}"
            echo "orig_cluster_repo=ghcr.io/${ORIG_OWNER}/sealos-cloud-${MODULE_NAME}-${COMP}"
            echo "cur_cluster_repo=ghcr.io/${REPO_OWNER}/sealos-cloud-${MODULE_NAME}-${COMP}"
          } >> "$GITHUB_OUTPUT"