name: Release

env:
  # Common versions
  GO_VERSION: "1.22"

on:
  workflow_dispatch:

  push:
    tags:
      - "*"

jobs:
  goreleaser:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu \
            libbtrfs-dev libgpgme-dev libdevmapper-dev \
            qemu-user-static binfmt-support

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean --release-footer-tmpl=scripts/release/footer.md.tmpl --release-header-tmpl=scripts/release/head.md.tmpl
          workdir: ./lifecycle
        env:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  changelog:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    needs:
      - goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch Current version
        id: get-current-tag
        uses: actions-ecosystem/action-get-latest-tag@v1.6.0
        with:
          semver_only: true
      - run: git fetch --prune --prune-tags
      - run: git tag -l 'v*'
      - name: Generator changelog
        env:
          REPOSITORY: ${{ github.repository }}
        run: ./scripts/changelog.sh "${REPOSITORY}"
      - uses: peter-evans/create-pull-request@v5
        with:
          title: 'docs: Automated Changelog Update for ${{steps.get-current-tag.outputs.tag }}'
          body: |
            copilot:all
            
            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          commit-message: |
            🤖 add release changelog for ${{steps.get-current-tag.outputs.tag }}.
          branch: changelog-${{steps.get-current-tag.outputs.tag }}
          base: main
          signoff: true
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}