name: Default sealos workflow entry

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "lifecycle/**"
      - "!**/*.md"
      - "!**/*.yaml"
      - "!**/*.yml"

  pull_request:
    branches: [ "*" ]
    paths:
        - "lifecycle/**"
        - "!**/*.md"
        - "!**/*.yaml"
        - "!**/*.yml"

jobs:
  check-license:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check License
        env:
          PROJECT_PATH: "lifecycle"
        run: cd "${PROJECT_PATH}" && make verify-license
  run-linter:
    uses: ./.github/workflows/golangci-lint.yml
    with:
      workdir: "lifecycle"
      module_path: ""
      version: "1.22"
